/** Tokens visuais alinhados ao Microsoft Excel (grade, fonte e cores padrão). */
export const EXCEL_SHEET = {
  fontFamily: 'Calibri, "Segoe UI", Arial, sans-serif',
  fontSize: '11px',
  lineHeight: 1.2,
  borderColor: '#d4d4d4',
  border: '1px solid #d4d4d4',
  headerBg: '#f2f2f2',
  groupBg: '#d9e1f2',
  selectHeaderBg: '#e7e6e6',
  cellBg: '#ffffff',
  emptyRowBg: '#fafafa',
  selectedBg: '#d6eaf8',
  hoverBg: '#eef6fc',
  text: '#000000',
  mutedText: '#595959',
  toolbarBg: '#f3f3f3',
  toolbarBorder: '#d4d4d4',
  sheetBg: '#ffffff',
  finalizedCheck: '#217346',
} as const
