/** Clínicas típicas de hospital naval / hospital geral (ordem alfabética). */
export const CLINICAS_HOSPITAL = [
  'Clínica de Alergia e Imunologia',
  'Clínica de Anestesiologia',
  'Clínica de Angiologia',
  'Clínica de Cardiologia',
  'Clínica de Cirurgia Cardíaca',
  'Clínica de Cirurgia Geral',
  'Clínica de Cirurgia Pediátrica',
  'Clínica de Cirurgia Plástica',
  'Clínica de Cirurgia Torácica',
  'Clínica de Cirurgia Vascular',
  'Clínica de Clínica Médica',
  'Clínica de Coloproctologia',
  'Clínica de Dermatologia',
  'Clínica de Endocrinologia',
  'Clínica de Endoscopia',
  'Clínica de Gastroenterologia',
  'Clínica de Geriatria',
  'Clínica de Ginecologia e Obstetrícia',
  'Clínica de Hematologia',
  'Clínica de Infectologia',
  'Clínica de Mastologia',
  'Clínica de Nefrologia',
  'Clínica de Neurocirurgia',
  'Clínica de Neurologia',
  'Clínica de Oftalmologia',
  'Clínica de Oncologia',
  'Clínica de Ortopedia e Traumatologia',
  'Clínica de Otorrinolaringologia',
  'Clínica de Pediatria',
  'Clínica de Pneumologia',
  'Clínica de Proctologia',
  'Clínica de Psiquiatria',
  'Clínica de Radiologia e Diagnóstico por Imagem',
  'Clínica de Reumatologia',
  'Clínica de Urologia',
].sort((a, b) => a.localeCompare(b, 'pt-BR', { sensitivity: 'base' }))
