/** Extensões aceitas no anexo ao enviar planilha (documentos, planilhas e texto). */
export const PLANILHA_ANEXO_EXTENSIONS = [
  // Documentos / texto (pedido)
  '.doc',
  '.docx',
  '.docm',
  '.dot',
  '.dotx',
  '.dotm',
  '.odt',
  '.ott',
  '.rtf',
  '.txt',
  '.text',
  '.md',
  '.markdown',
  '.tex',
  '.latex',
  '.pdf',
  '.pdfa',
  '.ps',
  '.eps',
  '.xps',
  '.oxps',
  '.pages',
  '.wps',
  '.wpd',
  '.wp',
  '.abw',
  '.sxw',
  '.stw',
  '.sdw',
  '.hwp',
  '.hwpx',
  '.html',
  '.htm',
  '.xhtml',
  '.xml',
  '.mht',
  '.mhtml',
  '.fb2',
  '.epub',
  '.epub3',
  '.mobi',
  '.azw',
  '.azw3',
  '.kfx',
  '.djvu',
  '.cbz',
  '.cbr',
  '.c',
  '.h',
  '.cpp',
  '.hpp',
  '.java',
  '.py',
  '.js',
  '.ts',
  '.jsx',
  '.tsx',
  '.cs',
  '.php',
  '.rb',
  '.go',
  '.rs',
  '.swift',
  '.kt',
  '.kts',
  '.dart',
  '.scala',
  '.sh',
  '.bash',
  '.zsh',
  '.ps1',
  '.bat',
  '.cmd',
  '.sql',
  '.lua',
  '.r',
  '.csv',
  '.tsv',
  '.json',
  '.jsonl',
  '.yaml',
  '.yml',
  '.toml',
  '.ini',
  '.cfg',
  '.conf',
  '.properties',
  '.log',
  '.env',
  '.bib',
  '.bibtex',
  '.ris',
  '.enl',
  '.cls',
  '.sty',
  '.dtx',
  '.ltx',
  '.mdown',
  '.mkd',
  '.mdwn',
  '.rst',
  '.textile',
  '.adoc',
  '.asciidoc',
  '.org',
  '.wiki',
  '.rtfd',
  '.fodt',
  // Excel / planilhas
  '.xls',
  '.xlsx',
  '.xlsm',
  '.xlsb',
  '.xlt',
  '.xltx',
  '.xltm',
  '.ods',
  '.fods',
  '.ots',
  '.numbers',
  // LibreOffice apresentação/desenho comuns
  '.odp',
  '.otp',
  '.odg',
  '.fodp',
] as const

/** Valor do atributo `accept` do input de arquivo. */
export const PLANILHA_ANEXO_ACCEPT = PLANILHA_ANEXO_EXTENSIONS.join(',')

const EXTENSION_SET = new Set(
  PLANILHA_ANEXO_EXTENSIONS.map((ext) => ext.toLowerCase()),
)

export function isPlanilhaAnexoFileName(fileName: string): boolean {
  const lower = fileName.trim().toLowerCase()
  const dot = lower.lastIndexOf('.')
  if (dot < 0) return false
  return EXTENSION_SET.has(lower.slice(dot))
}

export function filterPlanilhaAnexoFiles(files: FileList | File[]): File[] {
  return Array.from(files).filter((file) => isPlanilhaAnexoFileName(file.name))
}
